import type {Metadata} from "next";
import {Inter} from "next/font/google";
import type React from "react";
import "./globals.css";
import {ThemeProvider} from "@/components/ui/theme-provider";
import {SWRProvider} from "@/providers/swr";

const inter = Inter({
  variable: "--font-geist-sans",
    subsets: ["latin", "cyrillic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en" suppressHydrationWarning>
      <body
          className={`${inter.variable} antialiased`}
      >
      <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
      >
          <SWRProvider>
              {children}
          </SWRProvider>
      </ThemeProvider>
      </body>
    </html>
  );
}
